
# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup


import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, 'README.rst')
if os.path.exists(readme_path):
    with open(readme_path, 'rb') as stream:
        readme = stream.read().decode('utf8')


setup(
    long_description=readme,
    name='oorlu-cli',
    version='0.1.0',
    description='Simple URL shortener CLI written in Python',
    python_requires='==3.*,>=3.6.0',
    project_urls={"repository": "https://github.com/adamwojt/oorlu-cli"},
    author='Adam W.',
    author_email='adam1edinburgh@gmail.com',
    license='MIT',
    keywords='oorlu-cli',
    classifiers=['Development Status :: 2 - Pre-Alpha', 'Intended Audience :: Developers', 'Natural Language :: English', 'Programming Language :: Python', 'Programming Language :: Python :: 3', 'Programming Language :: Python :: 3.6', 'Programming Language :: Python :: 3.7', 'Programming Language :: Python :: 3.8', 'Programming Language :: Python :: Implementation :: CPython', 'Programming Language :: Python :: Implementation :: PyPy', 'Topic :: Software Development'],
    entry_points={"console_scripts": ["oorlu = oorlu_cli.cli:main"]},
    packages=['oorlu_cli'],
    package_dir={"": "src"},
    package_data={},
    install_requires=['click==7.*,>=7.0.0', 'requests==2.*,>=2.13.0'],
    extras_require={"dev": ["pip==19.*,>=19.2.3", "pytest==4.*,>=4.6.5", "pytest-runner==5.*,>=5.1.0", "wheel==0.*,>=0.33.6"]},
)
